server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://129.226.133.70:3306/kettle-reource?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

pagehelper:
  helper-dialect: mysql
  params: count=countsql
  reasonable: true
  support-methods-arrguments: true

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

#打印sql语句
logging:
  level:
    com.example.demo.dao: debug

kettle:
  resource-name: kettle-resource
  type: mysql
  access: jdbc
  host: 192.168.1.8
  db-name: kettle-reource
  port: 3306
  db-user: root
  db-password: root
  resource-username: admin
  resource-password: admin
